# IMAGEN MODELO
FROM eclipse-temurin:23.0.2_7-jdk

# INFORMAR EL PUERTO DONDE SE EJECUTA EL CONTENEDOR (INFORMATIVO)
EXPOSE 8080

# DEFINIR DIRECTORIO RAIZ DE NUESTRO DIRECTORIO
WORkDIR /root

#COPIAR Y PEGAR ARCHIVOS DENTRO  DEL CONTENEDOR
COPY ./pom.xml  /root
COPY ./.mvn  /root/.mvn
COPY ./mvnw  /root

ENV SPRING_DATASOURCE_URL=jdbc:mysql://mysql_database:3306/red_social_intereses_comunes
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=12345678
ENV MYSQL_ROOT_PASSWORD=12345678
ENV MYSQL_ROOT_PASSWORD=red_social_intereses_comunes

# DAR PERMISOS DE EJECUCIÓN AL SCRIPT mvnw
RUN chmod +x ./mvnw

#DESCARGAR LAS DEPENDECIAS
RUN ./mvnw dependency:go-offline

# COPIAR EL CODIGO FUENTE DENTRO DEL CONTENEDOR
COPY ./src  /root/src

#CONSTRUIR NUESTRA APLICACION
RUN ./mvnw clean install -DskipTests

# LEVANTAR NUESTRA APLICACION CUANDO EL CONTENEDOR INCIE
ENTRYPOINT ["java","-jar","/root/target/interesescomunes-0.0.1-SNAPSHOT.jar"]


