services:
  spring-api:
    image: spring-api
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql
    volumes:
      - spring-upload-volume:/app/uploads

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: red_social_intereses_comunes
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:
volumes:
  mysql-volume:
  spring-upload-volume:

