app:
  file:
    storage:
      path: ./uploads
    base-url: /api/files
    max-file-size: 5MB
    allowed-types:
      - image/jpeg
      - image/png
      - image/gif

spring:
  application:
    name: red-social
    jackson:
      default-property-inclusion: non_null
      property-naming-strategy: SNAKE_CASE
  datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: create
  logging:
    level:
      org.hibernate.SQL: debug


jwt:
  secret:
    key:
      private: DLi8EXyQQkB89la1EOeDgBWux/SNJALhtkDzWzSBqtU=
  time:
    expiration: 1800000

security:
  jwt:
    user:
      generator: AUTHOJWT-BACKEND



